from glob import glob
import os

folder = "./polyfill-libraries/3.111.0"
files = glob(folder + "/*/meta.json")

print("//! Metadata files")
print("//!")
print("//! DO NOT EDIT MANUALLY")
print("//! generated by: python3 gen.py > library/src/meta.rs")

def key(name):
    return "FILE_" + name \
        .replace("/", "_") \
        .replace(".", "_") \
        .replace("-", "_") \
        .replace("~", "_") \
        .replace("@", "_") \
        .upper()

for file in files:
    f = open(file, "r")
    contents = f.read();
    f.close()

    name = key(file.replace(folder, ""))

    print("const %s: &str = r#\"%s\"#;" % (name, contents))


print("")
print("pub(crate) fn lookup(n: &str) -> Option<&'static str> {")
print("  match n {")

for file in files:
    name = file.replace(folder, "")
    print("    \"%s\" => Some(%s)," % (name, key(name)))

print("    _ => None,")
print("  }")
print("}")
